name: Validate props.conf content
on:
  pull_request:
    branches:
      - main
    paths:
      - 'manager-apps/**'

jobs:
  check-props:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for props.conf
      id: check-props
      run: |
        if [ -f "manager-apps/**/local/props.conf" ]
        then
            echo "props.conf exists."
        else
            echo "props.conf does not exist."
        fi

    # - name: Post comment on failure
    #   if: failure()
    #   uses: actions/github-script@v6
    #   with:
    #     script: |
    #       const fs = require('fs');
    #       const result = fs.readFileSync('result.txt', 'utf8');
    #       github.rest.issues.createComment({
    #         issue_number: context.issue.number,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         body: result
    #       });